-------------------------------------------------------------------------------
Test set: in.thamimsubansait.doboo.TestCreateTask
-------------------------------------------------------------------------------
Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.064 s <<< FAILURE! - in in.thamimsubansait.doboo.TestCreateTask
in.thamimsubansait.doboo.TestCreateTask.testCreateTaskWithValidInput()  Time elapsed: 0.016 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: in.thamimsubansait.doboo.exception.ValidationException: Invalid Date or Invalid date Format
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:54)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:37)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3135)
	at in.thamimsubansait.doboo.TestCreateTask.testCreateTaskWithValidInput(TestCreateTask.java:29)
Caused by: in.thamimsubansait.doboo.exception.ValidationException: Invalid Date or Invalid date Format
	at in.thamimsubansait.doboo.service.TaskService.create(TaskService.java:33)
	at in.thamimsubansait.doboo.TestCreateTask.lambda$testCreateTaskWithValidInput$0(TestCreateTask.java:30)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:50)
	... 16 more

